# Generated by Django 4.1.3 on 2023-03-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='how_you_found_us',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.how_did_you_meet_us'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='education',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.education'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='occupation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.occupation'),
        ),
    ]
