# Generated by Django 4.1.3 on 2023-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='state',
            field=models.CharField(blank=True, choices=[('a', 'Aceptado'), ('d', 'Denegado'), ('r', 'Redirigido'), ('p', 'Pendiente')], default='p', help_text='Estado de la solicitud', max_length=1),
        ),
    ]
