# Generated by Django 4.1.3 on 2023-03-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_petition_state'),
    ]

    operations = [
    ]
