# Generated by Django 4.1.3 on 2023-03-08 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_petition_state'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today, help_text='Dia del evento')),
                ('start_time', models.TimeField(default=datetime.time(13, 27, 26, 160768), help_text='Inicio del evento')),
                ('end_time', models.TimeField(default=datetime.time(13, 27, 26, 160768), help_text='Final del evento')),
                ('title', models.TextField(default='Evento', help_text='Titulo del evento')),
                ('notes', models.TextField(blank=True, help_text='Notas del evento', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
