# Generated by Django 4.1.3 on 2023-03-08 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_massage_petition_message_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(13, 28, 0, 140045), help_text='Final del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(13, 28, 0, 140045), help_text='Inicio del evento'),
        ),
    ]
