# Generated by Django 4.1.3 on 2023-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_massage_petition_message'),
    ]

    operations = [
    ]
