# Generated by Django 4.1.3 on 2023-03-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_petition_massage_petition_message'),
        ('main', '0012_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
    ]
