# Generated by Django 4.1.3 on 2023-03-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20230314_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('is_nantik', 'Nantik admin'), ('is_immune', 'Immune admin'))},
        ),
    ]
