# Generated by Django 4.1.3 on 2023-03-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customuser_options_and_more'),
    ]

    operations = [
    ]
